In [1]:
import os
from dotenv import load_dotenv
import requests

load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')


In [2]:
from openai import OpenAI

# .env 파일에서 api키 이름을 OPENAI_API_KEY로 넣으면 OpenAI안에 api_key 값을 전달하지 않아도 자동으로 api 키를 전달함
client = OpenAI()

response = client.responses.create(
  model="gpt-5.6",
  instructions="AI와 딥러닝, LLM에 대한 전문가",
  input="GPT 이후의 LLM 모델들의 발전 이력에 대해 설명해"
)

print(response)

print('------')
print(response.output_text)

Response(id='resp_0e298f32dc751a87006a619a894d88819aa460baee052a36a0', created_at=1784781449.0, error=None, incomplete_details=None, instructions='AI와 딥러닝, LLM에 대한 전문가', metadata={}, model='gpt-5.6-sol', object='response', output=[ResponseReasoningItem(id='rs_0e298f32dc751a87006a619a8a1850819ab0519ed70e5f99fc', summary=[], type='reasoning', content=[], encrypted_content='gAAAAABqYZrJdqV1czNKe6wkwv_kfb2D3yF_WETrK87yBAOMCPgr6VI53FpIMD89YjhIHAq5cg59FwhYd_4FNnXfF8eAVEYyRyTOLcLdysSKVeiTV_mlb9FsgbcptqC5_8kJ9v3CavmrVY7FYXKAwEYE3aKJA8mai4IAWO-Sqio-rwZd1Va8xCJOt1DACV090Bd-z7SdtzmhfD1JMD4uaBqRkUAmsMs5FXr4qfOV8q8NE-pGTynpeW8oXkiD_2BTTk-GDy9YmbvJuA7MmVjUcSPxYUgINXun4yVSbkMIB67ldkmoeErsrJ1j6siQ6T_BeOBnMOqeOiQawXaHe9oMQjqiYjkh3McEXzMKYHl7JzjQ42chJ1aLbf25BjtjqWDlr2Ab5qp5d2aMQ2XKbqakhZLs-_A5E1X3LEqhVuAjS4kn8EACn2M4YIO4TTeImy-kpmsbcnuBonFfkn9XEW_SAgdJqkbUNk5Gfh1T3Z6RDz_DjlZpWdBkE4Vl_sO0tflX_uCIHGpE1yu5pSMUNdGx4097rYdVFYrrDysCl0Cl1U0zxPA4fu1IFJ_0WnHR5cObSL09SqBwca7N61Qxm3PWck_aw-4p-ccM8uKvQ7fVroDs6oCZX1

# 랭체인으로 연결

- HumanMessage : 사람이 입력값으로 넣은 질문
- AIMessage : 모델 호출의 결과 -> 즉 모델이 생성한 출력
- SystemMessage : 시스템 프롬프트 / 모델의 태도, 역할, 규칙을 생성
- ToolMessage : tool의 호출 결과를 모델에 다시 전달할 떄 사용

In [3]:
from langchain_openai import ChatOpenAI
from langchain.messages import HumanMessage, AIMessage, SystemMessage

model = ChatOpenAI(model="gpt-5.6")

model.invoke([HumanMessage("안녕! 랭체인에 대해 설명해줘")])

AIMessage(content='안녕하세요! **랭체인(LangChain)**은 대규모 언어 모델(LLM)을 활용한 애플리케이션을 쉽게 만들도록 돕는 **Python·JavaScript/TypeScript 프레임워크**입니다.\n\n단순히 GPT 같은 모델을 호출하는 것을 넘어, **외부 데이터·도구·대화 기록·작업 흐름**을 연결할 수 있게 해줍니다.\n\n## 주요 기능\n\n- **모델 연동**  \n  OpenAI, Anthropic, Google 등 다양한 LLM을 공통 인터페이스로 사용합니다.\n\n- **프롬프트 관리**  \n  템플릿을 사용해 입력값에 따라 프롬프트를 동적으로 구성합니다.\n\n- **체인(Chain)**  \n  여러 처리 단계를 순서대로 연결합니다.  \n  예: 질문 입력 → 문서 검색 → 프롬프트 생성 → 답변 생성\n\n- **RAG**  \n  PDF, 데이터베이스, 사내 문서 등을 검색한 뒤 관련 내용을 LLM에 전달해 답변하게 합니다.\n\n- **도구 호출과 에이전트**  \n  LLM이 검색, 계산기, 데이터베이스, 외부 API 등의 도구를 선택해 사용하도록 구성합니다.\n\n- **구조화된 출력**  \n  모델의 답변을 JSON이나 정의된 데이터 객체 형태로 받을 수 있습니다.\n\n## 관련 생태계\n\n- **LangChain**: 모델, 프롬프트, 검색기, 도구 등을 연결하는 기본 컴포넌트\n- **LangGraph**: 상태와 분기, 반복이 있는 복잡한 에이전트 워크플로 구성\n- **LangSmith**: 실행 추적, 디버깅, 평가 및 모니터링\n- **LangServe**: 랭체인 기반 기능을 API로 제공할 때 사용하는 도구\n\n## 간단한 예시\n\n```python\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate

In [4]:
# Langchain Docs에서 설명하는 init_chat_model로 모델 생성
import os
from langchain.chat_models import init_chat_model

model = init_chat_model(
        "gpt-5.6",
        temperature = 0.4
        )

response = model.invoke("만화 블리치에 대해서 알아?")
response

AIMessage(content='네, 알아요. **《블리치(BLEACH)》**는 쿠보 타이토가 그린 일본 만화로, 유령을 볼 수 있는 고등학생 **쿠로사키 이치고**가 사신 **쿠치키 루키아**의 힘을 넘겨받으면서 벌어지는 이야기를 다룹니다.\n\n주요 요소는 다음과 같아요.\n\n- **사신과 참백도**, 그리고 필살 해방인 **시해·만해**\n- 사신들이 사는 **소울 소사이어티**\n- 적대 세력인 **호로·아란칼·퀸시**\n- 대표 장편: **사신대행 편**, **소울 소사이어티 편**, **아란칼 편**, **천년혈전 편**\n\n원작 만화는 완결됐고, 애니메이션 **《블리치 천년혈전편》**으로 마지막 이야기도 제작되고 있습니다. 캐릭터, 줄거리, 능력, 세계관 중 무엇이 궁금한가요?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 231, 'prompt_tokens': 15, 'total_tokens': 246, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.6-sol', 'system_fingerprint': None, 'id': 'chatcmpl-E4fUovpBzDrS4PEJSPIisddGBHAQQ', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019f8d44-e210-7af

- LangChain에서 Prompt 추가

In [5]:
messages = [
  # SystemMessage를 이용해서 Role 부여
  SystemMessage("너는 애니메이션/만화 전문가야. 스포일러 없이 핵심만 간단히 설명해줘."),
  HumanMessage("만화 블리치 주인공인 이치고에 대해서 설명해줘")
]

response = model.invoke(messages)
response.content

'**쿠로사키 이치고**는 《블리치》의 주인공으로, 주황색 머리와 강한 인상이 특징인 고등학생입니다.\n\n- 어릴 때부터 영혼을 볼 수 있으며, 사건을 계기로 **사신의 힘**을 얻어 ‘대행 사신’으로 활동합니다.\n- 거칠고 무뚝뚝해 보이지만, 실제로는 **가족과 동료를 지키려는 책임감**이 매우 강합니다.\n- 거대한 참백도 **‘참월’**을 사용하며, 빠른 속도와 강력한 검격이 중심인 전투 스타일을 보여줍니다.\n- 싸움을 즐기기보다는 소중한 사람을 보호하기 위해 강해지는 **수호자형 주인공**입니다.\n\n작품이 진행될수록 자신의 힘과 정체성을 이해하며 성장하는 것이 이치고 이야기의 핵심입니다.'

- ChatPromptTemplate을 이용해서 Prompt를 다양하게 만들기

In [6]:
from langchain_core.prompts import ChatPromptTemplate

# ChatPromptTemplate을 이용하면 메세지 내부에 변수 자리를 마련해놓을 수 있다
prompt = ChatPromptTemplate([
    ("system", "너는 {genre} 전문가야. 스포일러 없이 핵심만 간단히 설명해줘."),
    ("system", "답변을 출력할 때 Markdown 양식 말고 순수 텍스트로만 출력할 것"),
    ("human", "{title}에 대해서 알아?"),
])

# 프롬프트를 실제 메시지로 변환
prompt_value = prompt.invoke({"genre": "만화", "title": "원피스"})

response = model.invoke(prompt_value)
response.content

'네. 『원피스』는 오다 에이치로의 해적 모험 만화로, 주인공 몽키 D. 루피가 동료들과 함께 전설의 보물 ‘원피스’를 찾아 바다를 여행하는 이야기입니다. 모험, 우정, 자유, 세계의 비밀을 중심으로 전개됩니다.'

- Chaining으로 모델과 프롬프트 연결하기   
prompt | model | output_parser 방식으로 데이터를 왼쪽에서 오른쪽으로 보내는 느낌

In [7]:
# 프롬프트와 모델을 분리해서 구현
chained_model = prompt | model
response = chained_model.invoke({"genre" : "만화", "title" : "원피스"})
response.content

'네, 알아요. 《원피스》는 오다 에이치로의 해적 모험 만화로, 주인공 몽키 D. 루피가 동료들과 함께 전설의 보물 ‘원피스’를 찾아 위대한 항로를 여행하는 이야기입니다. 모험, 우정, 자유, 거대한 세계관이 핵심 매력입니다.'

- output_parser 까지 연결해보기

In [8]:
from langchain_core.output_parsers import StrOutputParser

parser = StrOutputParser()

full_model = prompt | model | parser

# parser를 연결해서 response.content를 안해도 텍스트만 불러온다
full_model.invoke({"genre" : "만화", "title" : "원피스"})

'네, 알아요. 《원피스》는 오다 에이치로의 해적 모험 만화로, 주인공 몽키 D. 루피와 동료들이 전설의 보물 ‘원피스’를 찾아 바다를 여행하는 이야기입니다. 우정, 자유, 꿈을 중심으로 한 방대한 세계관이 특징이에요.'

# 코사인 유사도

In [9]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

v1 = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

v2 = np.array([
  [10, 20, 30],
  [-20, -50, -70]
])

cos_sim = cosine_similarity(v1, v2)
print(cos_sim)

[[ 1.         -0.99862543]
 [ 0.97463185 -0.96776208]]


In [13]:
# 무료 버전을 이용한 벡터화
from sentence_transformers import SentenceTransformer

# 1. 모델 불러오기
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

# 2. 임베딩 생성할 문장들 => 문장 사전
sentences = [
    "고양이가 창가에서 햇볕을 쬐고 있다",
    "새끼 고양이가 실타래를 가지고 논다",
    "강아지가 공원에서 뛰어다닌다",
    "강아지가 주인을 보고 꼬리를 흔든다",
    "호랑이가 숲속을 걸어 다닌다",
    "사자가 초원에서 사냥을 준비한다",
    "코끼리가 긴 코로 나뭇가지를 잡는다",
    "기린이 나무 위 잎을 먹는다",
    "원숭이가 바나나를 먹는다",
    "펭귄이 얼음 위에서 걸어간다",
    "사과가 빨갛게 익었다",
    "바나나가 노랗게 잘 익어 달콤하다",
    "포도가 달콤하고 신선하다",
    "빵이 오븐에서 갓 구워졌다",
    "라면이 뜨겁게 끓고 있다",
    "김치찌개에서 얼큰한 냄새가 난다",
    "초밥이 접시에 예쁘게 놓여 있다",
    "피자가 치즈로 가득 덮여 있다",
    "햄버거에 고기 패티가 두껍다",
    "커피 향이 방 안에 가득 퍼졌다",
    "서울의 남산타워가 빛나고 있다",
    "한강 다리 위에서 야경을 본다",
    "제주도의 바닷가가 파랗게 빛난다",
    "부산 해운대 해수욕장에 사람이 많다",
    "경복궁의 전통 건물이 웅장하다",
    "뉴욕의 자유의 여신상이 우뚝 서 있다",
    "파리의 에펠탑이 밤에 반짝인다",
    "런던의 빅벤 시계탑이 울린다",
    "도쿄의 시부야 거리가 붐빈다",
    "로마의 콜로세움이 고대의 흔적을 보여준다"
]

c:\Users\sb730\anaconda3\envs\deepl\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\sb730\anaconda3\envs\deepl\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sb730\.cache\huggingface\hub\models--jhgan--ko-sroberta-multitask. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activat

In [14]:
embedding = model.encode(sentences)
print(f'임베딩 벡터 수 : {len(embedding)}, 차원 : {embedding.shape}')

임베딩 벡터 수 : 30, 차원 : (30, 768)


In [15]:
embedding[0]

array([-3.10807198e-01, -7.71565437e-01,  6.14109457e-01,  1.37913179e+00,
        2.29712084e-01,  6.92956448e-01,  4.94495153e-01, -1.99370980e-01,
       -4.37072635e-01, -1.00595765e-01, -4.50879961e-01,  3.47338080e-01,
        4.74450260e-01,  1.16429366e-02,  3.46862465e-01,  2.18584463e-01,
       -1.67658314e-01,  1.43997267e-01, -7.00315058e-01,  7.37008750e-01,
       -7.05900371e-01, -9.57424715e-02, -1.75103188e-01, -2.34502718e-01,
       -6.54982865e-01,  5.81046045e-01, -6.91041946e-01,  2.53226310e-01,
        5.85312784e-01, -6.54737428e-02,  2.62539774e-01, -1.14242494e+00,
        4.03907776e-01,  1.16223760e-01,  2.62310579e-02, -1.45270020e-01,
        6.27244055e-01, -2.61913389e-01,  9.72486794e-01,  3.13363880e-01,
        3.39273810e-01, -4.72194672e-01, -6.30879030e-02, -2.40380898e-01,
        1.79844454e-01, -9.91072953e-01, -7.25039899e-01,  1.95220351e-01,
        8.64447877e-02, -1.92654297e-01, -3.10642272e-01,  2.24160198e-02,
        2.64692932e-01,  

In [16]:
print(len(embedding[0]))

768


### embedding vector 결과(위치) 확인하기
- TensorFlow Embedding Projector(https://projector.tensorflow.org/): 구글에서 제공하는 웹 사이트를 통해 직접 시각화
  - 1단계: Colab에서 생성한 embeddings 배열을 tsv 파일로 저장
  - 2단계: Embedding Projector 접속 후, 좌측 상단의 [Load] 버튼을 클릭
  - 3단계: Step 1에서 생성한 vectors.tsv를 Step 1(Load a TSV file of vectors)에, metadata.tsv를 Step 2(Load a TSV file of metadata)에 각각 업로드
  - 4단계: 우측의 'T-SNE'나 'PCA'를 선택하여 데이터가 어떻게 뭉쳐 있는지 확인


In [17]:
# 4. vectors.tsv 저장

with open('../실습 자료/vectors.tsv', 'w', encoding='utf-8') as f:
    for emb in embedding:
        f.write('\t'.join([str(x) for x in emb])+ '\n')

# 5. metadata.tsv 저장
with open('../실습 자료/metadata.tsv', 'w', encoding='utf-8') as f:
    for s in sentences:
        f.write(s + '\n')

In [18]:
# 6. 결과 확인
query = input('문장을 입력하세요.')

query_embedding = model.encode([query])

similarity = cosine_similarity(query_embedding, embedding)[0]
similarity

array([ 0.48900616,  0.46266478,  0.03910764,  0.11314938,  0.05864392,
        0.10009214,  0.08082779,  0.04889392,  0.00721912,  0.07581721,
       -0.0802967 , -0.03958719,  0.00058016,  0.20584062, -0.05986093,
       -0.02905973,  0.0345864 , -0.08275996,  0.16806129,  0.02480312,
        0.16025266,  0.13128546,  0.10130221,  0.04324827,  0.19214661,
        0.18993106,  0.14410886,  0.1346581 ,  0.13793987,  0.0856333 ],
      dtype=float32)

In [19]:
# 유사도가 높은 상위 2개의 문장 찾기
top2_idx = similarity.argsort()[-2:][::-1]
print(top2_idx)

[0 1]


In [20]:
print(f"입력된 문장 : {query}")

for idx in top2_idx:
  print(f"문장 : {sentences[idx]} /// 유사도 : {similarity[idx]:.4f}")

입력된 문장 : 고양이가 문에 서있다
문장 : 고양이가 창가에서 햇볕을 쬐고 있다 /// 유사도 : 0.4890
문장 : 새끼 고양이가 실타래를 가지고 논다 /// 유사도 : 0.4627


# OpenAI를 이용한 Embedding

In [24]:
client = OpenAI()

openai_man_embedding = client.embeddings.create(
  model = 'text-embedding-3-large',
  input = 'man'
)

man_vector = np.array(openai_man_embedding.data[0].embedding)
man_vector

array([ 0.0098877 ,  0.02897644, -0.00474548, ..., -0.00353622,
       -0.00544357,  0.00143814], shape=(3072,))

In [27]:
openai_woman_embedding = client.embeddings.create(
  model = 'text-embedding-3-large',
  input = 'woman'
)

woman_vector = np.array(openai_woman_embedding.data[0].embedding)
woman_vector

array([ 0.0196228 , -0.01291656, -0.00804138, ..., -0.01416016,
        0.00963593,  0.00363159], shape=(3072,))

In [28]:
result = cosine_similarity(man_vector.reshape(1, -1), woman_vector.reshape(1, -1))
result[0][0]

np.float64(0.5712402181459058)

- 문장을 이용한 벡터화

In [29]:
sentences = [
    "고양이가 창가에서 햇볕을 쬐고 있다",
    "새끼 고양이가 실타래를 가지고 논다",
    "강아지가 공원에서 뛰어다닌다",
    "강아지가 주인을 보고 꼬리를 흔든다",
    "호랑이가 숲속을 걸어 다닌다",
    "사자가 초원에서 사냥을 준비한다",
    "코끼리가 긴 코로 나뭇가지를 잡는다",
    "기린이 나무 위 잎을 먹는다",
    "원숭이가 바나나를 먹는다",
    "펭귄이 얼음 위에서 걸어간다",
    "사과가 빨갛게 익었다",
    "바나나가 노랗게 잘 익어 달콤하다",
    "포도가 달콤하고 신선하다",
    "빵이 오븐에서 갓 구워졌다",
    "라면이 뜨겁게 끓고 있다",
    "김치찌개에서 얼큰한 냄새가 난다",
    "초밥이 접시에 예쁘게 놓여 있다",
    "피자가 치즈로 가득 덮여 있다",
    "햄버거에 고기 패티가 두껍다",
    "커피 향이 방 안에 가득 퍼졌다",
    "서울의 남산타워가 빛나고 있다",
    "한강 다리 위에서 야경을 본다",
    "제주도의 바닷가가 파랗게 빛난다",
    "부산 해운대 해수욕장에 사람이 많다",
    "경복궁의 전통 건물이 웅장하다",
    "뉴욕의 자유의 여신상이 우뚝 서 있다",
    "파리의 에펠탑이 밤에 반짝인다",
    "런던의 빅벤 시계탑이 울린다",
    "도쿄의 시부야 거리가 붐빈다",
    "로마의 콜로세움이 고대의 흔적을 보여준다"
]

In [36]:
def get_embedding(text):
  res = client.embeddings.create(
    model = 'text-embedding-3-large',
    input = text
  )

  return res.data[0].embedding

sentence_vector = [get_embedding(s) for s in sentences]

sentence_vector = np.array(sentence_vector)
sentence_vector

array([[ 0.01009369,  0.00312233,  0.00322151, ..., -0.00632095,
        -0.00785828, -0.02119446],
       [-0.02101135, -0.02394104, -0.00449371, ...,  0.00368118,
         0.00468063, -0.01631165],
       [-0.00740051, -0.00920105,  0.00122833, ...,  0.00130844,
        -0.00985718, -0.01651001],
       ...,
       [ 0.03004456, -0.03619385, -0.00041151, ...,  0.00733185,
         0.00435257, -0.0103302 ],
       [ 0.04986572, -0.03970337,  0.0020237 , ..., -0.00449371,
        -0.00104618, -0.01596069],
       [-0.00181293, -0.01133728, -0.01422882, ...,  0.00652695,
        -0.01870728,  0.00800323]], shape=(30, 3072))

In [63]:
# 6. 결과 확인
query = input('문장을 입력하세요.')

query_embedding = get_embedding(query)
sentence_similarity = cosine_similarity([query_embedding], sentence_vector)[0]
sentence_similarity

array([0.6403387 , 0.44162831, 0.31540204, 0.38480197, 0.352243  ,
       0.24401715, 0.23927745, 0.28264397, 0.3270852 , 0.32612121,
       0.2267918 , 0.17123166, 0.18201262, 0.26755322, 0.1966154 ,
       0.22228421, 0.28814985, 0.24551978, 0.2223319 , 0.29690614,
       0.24503142, 0.22309834, 0.10867259, 0.14639616, 0.2045839 ,
       0.28549305, 0.17450008, 0.17763163, 0.20317808, 0.12923463])

In [ ]:
# 유사도가 높은 상위 2개의 문장 찾기
top2_idx = sentence_similarity.argsort()[-2:][::-1]
print(top2_idx)

[0 1]
<class 'numpy.int64'>


In [67]:
print(f"입력된 문장 : {query}")

for idx in top2_idx:
  print(f"문장 : {sentences[idx]} /// 유사도 : {sentence_similarity[idx]:.4f}")

입력된 문장 : 고양이가 문에 서있다
문장 : 고양이가 창가에서 햇볕을 쬐고 있다 /// 유사도 : 0.6403
문장 : 새끼 고양이가 실타래를 가지고 논다 /// 유사도 : 0.4416
