In [1]:
import os
from dotenv import load_dotenv
import requests

load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')


In [2]:
from openai import OpenAI

# .env 파일에서 api키 이름을 OPENAI_API_KEY로 넣으면 OpenAI안에 api_key 값을 전달하지 않아도 자동으로 api 키를 전달함
client = OpenAI()

response = client.responses.create(
  model="gpt-5.6",
  instructions="AI와 딥러닝, LLM에 대한 전문가",
  input="GPT 이후의 LLM 모델들의 발전 이력에 대해 설명해"
)

print(response)

print('------')
print(response.output_text)

KeyboardInterrupt: 

# 랭체인으로 연결

- HumanMessage : 사람이 입력값으로 넣은 질문
- AIMessage : 모델 호출의 결과 -> 즉 모델이 생성한 출력
- SystemMessage : 시스템 프롬프트 / 모델의 태도, 역할, 규칙을 생성
- ToolMessage : tool의 호출 결과를 모델에 다시 전달할 떄 사용

In [ ]:
from langchain_openai import ChatOpenAI
from langchain.messages import HumanMessage, AIMessage, SystemMessage

model = ChatOpenAI(model="gpt-5.6")

model.invoke([HumanMessage("안녕! 랭체인에 대해 설명해줘")])

AIMessage(content='안녕하세요! **랭체인(LangChain)**은 대규모 언어 모델(LLM)을 활용한 애플리케이션을 쉽게 개발하도록 돕는 오픈소스 프레임워크입니다. Python과 JavaScript/TypeScript를 지원합니다.\n\n### 핵심 개념\n\n- **Models**: OpenAI, Anthropic, Google 등 다양한 LLM을 공통 인터페이스로 연결\n- **Prompt**: 프롬프트 템플릿을 만들어 입력을 일관되게 구성\n- **Chains**: 프롬프트, 모델 호출, 데이터 처리 등의 여러 단계를 연결\n- **Tools & Agents**: LLM이 검색, 계산기, API, 데이터베이스 같은 도구를 상황에 맞게 선택·호출\n- **Retrieval / RAG**: 문서를 검색한 뒤 관련 내용을 LLM에 제공하여 답변의 정확성과 근거를 강화\n- **Memory / State**: 대화 기록이나 워크플로 상태를 유지\n- **Observability**: LangSmith를 통해 실행 흐름을 추적하고 평가·디버깅\n\n### 어떤 데 사용하나요?\n\n- 문서 기반 질의응답 챗봇\n- 사내 지식 검색 및 고객 상담 자동화\n- SQL·검색 API와 연결된 AI 어시스턴트\n- 문서 요약 및 정보 추출\n- 여러 도구를 사용하는 AI 에이전트\n\n### 간단한 Python 예시\n\n```bash\npip install langchain langchain-openai\n```\n\n```python\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_template(\n    "{topic}을 초보자에게 세 문장으로 설명해줘."\n)\n\nmodel = ChatOpenAI(model="gpt-4.1-mini")\nchain = promp

In [ ]:
# Langchain Docs에서 설명하는 init_chat_model로 모델 생성
import os
from langchain.chat_models import init_chat_model

model = init_chat_model(
        "gpt-5.6",
        temperature = 0.4
        )

response = model.invoke("만화 블리치에 대해서 알아?")
response

AIMessage(content='네, 알아요. **《블리치(BLEACH)》**는 쿠보 타이토가 그린 일본 소년만화로, 영혼을 볼 수 있는 고등학생 **쿠로사키 이치고**가 사신 **쿠치키 루키아**에게 힘을 넘겨받으면서 벌어지는 이야기입니다.\n\n주요 설정은 **사신**, **호로**, **소울 소사이어티**, **참백도**, **아란칼**, **퀸시** 등이며, 대표적인 장편 에피소드로는:\n\n- 사신대행 편\n- 소울 소사이어티 편\n- 아란칼·아이젠 편\n- 사신대행 소실 편\n- 천년혈전 편\n\n등이 있습니다. 원작 만화는 완결됐고, 애니메이션도 마지막 장인 **‘천년혈전 편’**이 제작되었습니다. 캐릭터, 줄거리, 능력, 설정 중 어떤 부분이 궁금하신가요?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 224, 'prompt_tokens': 15, 'total_tokens': 239, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cache_write_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5.6-sol', 'system_fingerprint': None, 'id': 'chatcmpl-E4cZlcEupOQWaSLwqcs4yZi6BWuJ3', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019f8c99-9b71-7780-9c39-c5ee03

- LangChain에서 Prompt 추가

In [ ]:
messages = [
  # SystemMessage를 이용해서 Role 부여
  SystemMessage("너는 애니메이션/만화 전문가야. 스포일러 없이 핵심만 간단히 설명해줘."),
  HumanMessage("만화 블리치 주인공인 이치고에 대해서 설명해줘")
]

response = model.invoke(messages)
response.content

'**쿠로사키 이치고**는 《블리치》의 주인공입니다.\n\n- **정체:** 영혼을 볼 수 있는 고등학생으로, 어떤 사건을 계기로 **사신의 힘**을 얻어 ‘사신대행’으로 활동합니다.\n- **성격:** 다소 거칠고 무뚝뚝하지만 책임감과 정의감이 강하며, 가족과 동료를 지키는 일을 가장 중요하게 여깁니다.\n- **전투 방식:** 참백도 **‘참월’**을 사용하는 검술과 강한 영압이 특징입니다.\n- **매력:** 강적과 싸우며 빠르게 성장하고, 여러 종류의 힘과 자신의 정체성을 고민하는 입체적인 캐릭터입니다.\n- **외형:** 눈에 띄는 주황색 머리 때문에 주변에서 불량학생으로 오해받기도 합니다.'

- ChatPromptTemplate을 이용해서 Prompt를 다양하게 만들기

In [ ]:
from langchain_core.prompts import ChatPromptTemplate

# ChatPromptTemplate을 이용하면 메세지 내부에 변수 자리를 마련해놓을 수 있다
prompt = ChatPromptTemplate([
    ("system", "너는 {genre} 전문가야. 스포일러 없이 핵심만 간단히 설명해줘."),
    ("system", "답변을 출력할 때 Markdown 양식 말고 순수 텍스트로만 출력할 것"),
    ("human", "{title}에 대해서 알아?"),
])

# 프롬프트를 실제 메시지로 변환
prompt_value = prompt.invoke({"genre": "만화", "title": "원피스"})

response = model.invoke(prompt_value)
response.content

'네. 《원피스》는 오다 에이치로의 해적 모험 만화로, 주인공 몽키 D. 루피가 동료들과 전설의 보물 ‘원피스’를 찾아 바다를 항해하는 이야기입니다. 모험, 우정, 자유를 중심으로 방대한 세계관과 복선이 특징입니다.'

- Chaining으로 모델과 프롬프트 연결하기   
prompt | model | output_parser 방식으로 데이터를 왼쪽에서 오른쪽으로 보내는 느낌

In [ ]:
# 프롬프트와 모델을 분리해서 구현
chained_model = prompt | model
response = chained_model.invoke({"genre" : "만화", "title" : "원피스"})
response.content

'네. 《원피스》는 오다 에이치로가 1997년부터 연재한 해적 모험 만화입니다. 주인공 몽키 D. 루피가 동료들과 함께 전설의 보물 ‘원피스’를 찾아 바다를 모험하는 이야기예요. 자유, 우정, 꿈을 중심으로 방대한 세계관과 치밀한 복선이 특징입니다.'

- output_parser 까지 연결해보기

In [ ]:
from langchain_core.output_parsers import StrOutputParser

parser = StrOutputParser()

full_model = prompt | model | parser

# parser를 연결해서 response.content를 안해도 텍스트만 불러온다
full_model.invoke({"genre" : "만화", "title" : "원피스"})

'네, 알아요. 《원피스》는 오다 에이치로의 해적 모험 만화로, 주인공 몽키 D. 루피가 동료들과 전설의 보물 ‘원피스’를 찾아 바다를 여행하는 이야기예요. 우정, 자유, 꿈을 중심으로 한 방대한 세계관이 특징입니다.'

# 코사인 유사도

In [3]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

v1 = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

v2 = np.array([
  [10, 20, 30],
  [-20, -50, -70]
])

cos_sim = cosine_similarity(v1, v2)
print(cos_sim)

[[ 1.         -0.99862543]
 [ 0.97463185 -0.96776208]]


In [4]:
# 무료 버전을 이용한 벡터화
from sentence_transformers import SentenceTransformer

# 1. 모델 불러오기
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

# 2. 임베딩 생성할 문장들 => 문장 사전
sentences = [
    "고양이가 창가에서 햇볕을 쬐고 있다",
    "새끼 고양이가 실타래를 가지고 논다",
    "강아지가 공원에서 뛰어다닌다",
    "강아지가 주인을 보고 꼬리를 흔든다",
    "호랑이가 숲속을 걸어 다닌다",
    "사자가 초원에서 사냥을 준비한다",
    "코끼리가 긴 코로 나뭇가지를 잡는다",
    "기린이 나무 위 잎을 먹는다",
    "원숭이가 바나나를 먹는다",
    "펭귄이 얼음 위에서 걸어간다",
    "사과가 빨갛게 익었다",
    "바나나가 노랗게 잘 익어 달콤하다",
    "포도가 달콤하고 신선하다",
    "빵이 오븐에서 갓 구워졌다",
    "라면이 뜨겁게 끓고 있다",
    "김치찌개에서 얼큰한 냄새가 난다",
    "초밥이 접시에 예쁘게 놓여 있다",
    "피자가 치즈로 가득 덮여 있다",
    "햄버거에 고기 패티가 두껍다",
    "커피 향이 방 안에 가득 퍼졌다",
    "서울의 남산타워가 빛나고 있다",
    "한강 다리 위에서 야경을 본다",
    "제주도의 바닷가가 파랗게 빛난다",
    "부산 해운대 해수욕장에 사람이 많다",
    "경복궁의 전통 건물이 웅장하다",
    "뉴욕의 자유의 여신상이 우뚝 서 있다",
    "파리의 에펠탑이 밤에 반짝인다",
    "런던의 빅벤 시계탑이 울린다",
    "도쿄의 시부야 거리가 붐빈다",
    "로마의 콜로세움이 고대의 흔적을 보여준다"
]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [10]:
embedding = model.encode(sentences)
print(f'임베딩 벡터 수 : {len(embedding)}, 차원 : {embedding.shape}')

임베딩 벡터 수 : 30, 차원 : (30, 768)


In [11]:
embedding[0]

array([-3.10807139e-01, -7.71565378e-01,  6.14109695e-01,  1.37913215e+00,
        2.29712173e-01,  6.92956388e-01,  4.94495541e-01, -1.99370861e-01,
       -4.37072188e-01, -1.00596063e-01, -4.50880140e-01,  3.47338110e-01,
        4.74450231e-01,  1.16429226e-02,  3.46862555e-01,  2.18584493e-01,
       -1.67658761e-01,  1.43997267e-01, -7.00315058e-01,  7.37008512e-01,
       -7.05900490e-01, -9.57422331e-02, -1.75103128e-01, -2.34502986e-01,
       -6.54983103e-01,  5.81045687e-01, -6.91042125e-01,  2.53226042e-01,
        5.85312665e-01, -6.54741451e-02,  2.62539625e-01, -1.14242518e+00,
        4.03907686e-01,  1.16223395e-01,  2.62313318e-02, -1.45269856e-01,
        6.27244592e-01, -2.61913329e-01,  9.72487152e-01,  3.13363940e-01,
        3.39273483e-01, -4.72194433e-01, -6.30881265e-02, -2.40380988e-01,
        1.79844677e-01, -9.91072953e-01, -7.25039959e-01,  1.95220172e-01,
        8.64450559e-02, -1.92654118e-01, -3.10642391e-01,  2.24162061e-02,
        2.64692992e-01,  

In [12]:
print(len(embedding[0]))

768


### embedding vector 결과(위치) 확인하기
- TensorFlow Embedding Projector(https://projector.tensorflow.org/): 구글에서 제공하는 웹 사이트를 통해 직접 시각화
  - 1단계: Colab에서 생성한 embeddings 배열을 tsv 파일로 저장
  - 2단계: Embedding Projector 접속 후, 좌측 상단의 [Load] 버튼을 클릭
  - 3단계: Step 1에서 생성한 vectors.tsv를 Step 1(Load a TSV file of vectors)에, metadata.tsv를 Step 2(Load a TSV file of metadata)에 각각 업로드
  - 4단계: 우측의 'T-SNE'나 'PCA'를 선택하여 데이터가 어떻게 뭉쳐 있는지 확인


In [13]:
# 4. vectors.tsv 저장

with open('../실습 자료/vectors.tsv', 'w', encoding='utf-8') as f:
    for emb in embedding:
        f.write('\t'.join([str(x) for x in emb])+ '\n')

# 5. metadata.tsv 저장
with open('../실습 자료/metadata.tsv', 'w', encoding='utf-8') as f:
    for s in sentences:
        f.write(s + '\n')

In [16]:
# 6. 결과 확인
query = input('문장을 입력하세요.')

query_embedding = model.encode([query])

similarity = cosine_similarity(query_embedding, embedding)[0]
similarity

array([ 0.83730257,  0.54492944,  0.04117958,  0.06324403,  0.074614  ,
        0.06263126,  0.17241311,  0.05325463,  0.08308885,  0.10663454,
        0.00557783,  0.05565368,  0.1599963 ,  0.14972663, -0.03026248,
        0.00895204,  0.12309775, -0.05565458,  0.10919134,  0.11781797,
        0.19114394,  0.3053286 ,  0.2144221 ,  0.0421038 ,  0.10322227,
        0.10305778,  0.27434945,  0.11397676,  0.19121318,  0.1345276 ],
      dtype=float32)

In [ ]:
# 유사도가 높은 상위 2개의 문장 찾기
top2_idx = similarity.argsort()[-2:][::-1]
print(top2_idx)

[0 1]


In [21]:
print(f"입력된 문장 : {query}")

for idx in top2_idx:
  print(f"문장 : {sentences[idx]} /// 유사도 : {similarity[idx]:.4f}")

입력된 문장 : 고양이가 창가에 있다
문장 : 고양이가 창가에서 햇볕을 쬐고 있다 /// 유사도 : 0.8373
문장 : 새끼 고양이가 실타래를 가지고 논다 /// 유사도 : 0.5449


- OpenAI를 이용한 Embedding

In [ ]:
client = OpenAI